---
- name: Attempting to set el6 nux_version fact
  tags: nux
  set_fact:
    nux_version: "0-2.el{{ nux_dist }}.nux"
  when: nux_dist == '6'

- name: Attempting to set el7 nux_version fact
  tags: nux
  set_fact:
    nux_version: "0-5.el{{ nux_dist }}.nux"
  when: nux_dist == '7'

- name: Attempting to generate temporary file
  tags: nux
  tempfile:
    prefix: nux.
    state: file
    suffix: .rpm
  register: nux_tempfile

- name: Attempting to download package to temporary location
  tags: nux
  get_url:
    dest: "{{ nux_tempfile.path }}"
    force: yes
    url: "{{ nux_baseurl }}/{{ nux_package }}-{{ nux_version }}.noarch.rpm"
  register: nux_get_url
  when: nux_tempfile is success

- name: Ensure that the {{ nux_package }} package is installed
  tags: nux
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: nux_yum
  with_items: "{{ nux_tempfile.path }}"
  when: nux_get_url is success

- name: Attempting to purge temporary package from the filesystem
  tags: nux
  file:
    path: "{{ nux_tempfile.path }}"
    state: absent
  when:
    - nux_tempfile is success
    - nux_yum is success

- name: Attempting to overlay nux repository configurations
  tags: nux
  become: true
  template:
    src: nux-dextop.repo.j2
    dest: /etc/yum.repos.d/nux-dextop.repo
    owner: root
    group: root
    mode: 0644
  when: nux_yum is success

- name: Ensure that the nux gpg keys are installed
  tags: nux
  become: true
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-nux.ro
    state: present
  when: nux_yum is success

- name: Ensure that the required nux packages are installed
  tags: nux
  become: true
  yum:
    disablerepo: "{{ nux_disablerepo|join(',') }}"
    enablerepo: "{{ nux_enablerepo|join(',') }}"
    name: "{{ item }}"
    state: present
  with_items: "{{ nux_packages }}"
  when:
    - nux_packages|length > 0
    - nux_yum is success
...
